<?php

namespace Instaphp\Utils\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 22:16:42.
 * @ignore
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Response
	 */
	protected $object;
	
	protected $mock_get;
	protected $mock_post;
	protected $mock_put;
	protected $mock_delete;
	protected $mock_head;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->mock_delete = file_get_contents(TEST_ROOT . '/mock/DELETE.mock');
		$this->mock_get = file_get_contents(TEST_ROOT . '/mock/GET.mock');
		$this->mock_head = file_get_contents(TEST_ROOT . '/mock/HEAD.mock');
		$this->mock_post = file_get_contents(TEST_ROOT . '/mock/POST.mock');
		$this->mock_put = file_get_contents(TEST_ROOT . '/mock/PUT.mock');
		
		$this->object = new Response($this->mock_get);
	}
	
	public function testInstanceOf()
	{
		$this->assertInstanceOf('\Instaphp\Utils\Http\Response', $this->object);
	}
	
	public function testGetResponse()
	{
		$this->assertEquals(200, $this->object->code);
		$this->assertNotEmpty($this->object->body);
		$json = json_decode($this->object->body, TRUE);
		$this->assertNotEmpty($json);
		$this->assertEquals('GET', $json['request_method']);
	}
	
	public function testPutResponse()
	{
		$this->object = new Response($this->mock_put);
		$this->assertNotEmpty($this->object->headers);
		$json = json_decode($this->object->body, TRUE);
		$this->assertEquals('PUT', $json['request_method']);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

}
