<?php

namespace Instaphp;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 22:16:22.
 * @ignore
 */
class InstaphpTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Instaphp
	 */
	protected $object;
	protected $config = [
        'api_endpoint' => 'https://api.instagram.com/{version}',
		'api_protocol' => 'https',
		'api_host' => 'api.instagram.com',
		'api_version' => 'v1',
		'client_id' => TEST_CLIENT_ID,
		'client_secret' => TEST_CLIENT_SECRET,
		'access_token' => '',
		'redirect_uri' => '',
		'http_useragent' => 'Instaphp/Guzzle/cUrl v3 (+http://instaphp.com)',
		'http_timeout' => 6,
		'http_connect_timeout' => 2,
        'log_enabled' => true,
        'log_level' => \Monolog\Logger::DEBUG,
        'log_path' => './instagram_test.log',
        'client_ip' => '127.0.0.1',
        'debug' => TRUE,
        'verify' => TRUE,
	];

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->config['access_token'] = '';
		$this->config['client_ip'] = '127.0.0.1';
		$this->object = new Instaphp($this->config);
        // print_r($this->object);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers Instaphp\Instaphp::__construct
	 */
	public function testConstructor()
	{
		$config = $this->config;
		$config['access_token'] = TEST_ACCESS_TOKEN;
		$obj = new Instaphp($config);
		$this->assertEquals(TEST_ACCESS_TOKEN, $obj->getAccessToken());
		$this->assertTrue($obj->isAuthorized());
	}

	/**
	 * @covers Instaphp\Instaphp::__get
	 */
	public function test__get()
	{
		$users = $this->object->users;
		$this->assertNotNull($users);
		$this->assertInstanceOf('\Instaphp\Instagram\Users', $users);
	}

	/**
	 * @covers Instaphp\Instaphp::__isset
	 * @todo   Implement test__isset().
	 */
	public function test__isset()
	{
		$media = $this->object->media;
		$this->assertTrue(isset($this->object->media));
	}

	/**
	 * @covers Instaphp\Instaphp::__unset
	 * @todo   Implement test__unset().
	 */
	public function test__unset()
	{
		$media = $this->object->media;
		$this->assertTrue(isset($this->object->media));
		unset($this->object->Media);
		$this->assertTrue(!isset($this->object->Media));
	}

	/**
	 * @covers Instaphp\Instaphp::setAccessToken
	 * @covers Instaphp\Instaphp::getAccessToken
	 */
	public function testSetAccessToken()
	{
		$this->assertEquals(TEST_ACCESS_TOKEN, $this->object->getAccessToken());
		$this->assertEquals(TEST_ACCESS_TOKEN, $this->object->Users->getAccessToken());

		$newAccessToken = '0123456789';

		$this->object->setAccessToken($newAccessToken);
		$this->assertEquals($newAccessToken, $this->object->getAccessToken());
		$this->assertEquals($newAccessToken, $this->object->Users->getAccessToken());
		$this->assertEquals($newAccessToken, $this->object->Tags->getAccessToken());

	}

	/**
	 * @covers Instagram\Instagram::isAuthorized
	 * @covers Instaphp\Instaphp::isAuthorized
	 */
	public function testIsAuthorized()
	{
		$this->object->setAccessToken(TEST_ACCESS_TOKEN);
		$this->assertTrue($this->object->isAuthorized());
	}

}
